version: "3.9"

services:
  backend:
    build: .
    container_name: skillmate-backend
    depends_on:
      - mongo
      - qdrant
    environment:
      MODEL_PROVIDER: ${MODEL_PROVIDER}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      MONGO_URI: ${MONGO_URI}
      MONGO_DB: ${MONGO_DB}
      SECRET_KEY: ${SECRET_KEY}
      QDRANT_HOST: ${QDRANT_HOST}
      QDRANT_PORT: ${QDRANT_PORT}
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    container_name: skillmate-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  qdrant:
    image: qdrant/qdrant:latest
    container_name: skillmate-qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  mongo_data:
  qdrant_data:
